services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fractal'
      - 'POSTGRES_PASSWORD=Fractal@2025'
      - 'POSTGRES_USER=fractal'
    ports:
      - '5435:5432'
