spring:
  application:
    name: Fractal-Human-Core-System
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        #hbm2ddl:
         # import_files: schema.sql
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
server:
  port: 8585