spring:
  application:
    name: Fractal-Human-Core-System
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        #hbm2ddl:
         # import_files: schema.sql
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
server:
  port: 8585

jwt:
  secret: "fractalJwtSecretKey@2025strong&safe!"
  expiration: 36000000 # 10 hours
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: strongpassword
  bucket: app-files

resource-storage:
  root-path: "./FILE-STORAGE"
  employee: "${resource-storage.root-path}/employee/"
  candidate: "${resource-storage.root-path}/candidate/"
  identification-document: "${resource-storage.root-path}/identification-document/"
  education: "${resource-storage.root-path}/education/"
  military-service: "${resource-storage.root-path}/military-service/"
  order: "${resource-storage.root-path}/order/"
  agreement: "${resource-storage.root-path}/agreement/"
  learning: "${resource-storage.root-path}/learning/"
  document-template-manager: "${resource-storage.root-path}/document-template-manager/"


